version: "3"
services:
    # server:
    #     build: ./server
    #     volumes:
    #         - ./server:/usr/src/app
    #     ports:
    #         - 5001:80
    server:
        build: ./server
        volumes:
            - ./server:/usr/src/app
        ports:
            - 5001:80
    client:
        build: ./client
        volumes:
            - ./client:/usr/src/app
        ports:
            - 5000:3000
            